### ISSUE TITLE
Not executable inside of XOSL (with CTRL+P) - hangs on startup

### ISSUE THREAD

**Issue by h0ly0ne** [binary-manu/rpm#3]
After getting the compilation to run within my virtual environment it seems that the original 2.44
(commit #e9d603d) works flawlessly when reintegration into the XOSL images. Current master
just tries to load and then hangs the whole system.

Within XOSL the binary is being loaded in 32k chunks (`FileSystem->ReadFile("XRPART??XXF",Ptr?)`)
and then executed with following ASM-Code-Fragment:

```
asm {
		xor	ax,ax
		mov es,ax
		push 0x1000
	    push 0x0200
		retf
	}
```

As the major changes are within the part.cpp/part.h for integrating the load/save mechanism I suspect
to go something wrong inside there. As I am not really able to get some exceptions and/or error messages
inside XOSLAPP this information is maybe some sort of help for you.

**Comment by binary-manu** [comment]
@h0ly0ne The `PART.EXE` built from the latest commit exceeds the limit of 64Kib (32KiB x 2 segments) that XOSL loads, as it amounts to about 78KiB. I assume you patched XOSL to load additional segments. Can you share your patch?

**Comment by binary-manu** [comment]
OK I got it. This is actually an XOSL issue.

XOSL loads RPM at address 1000:0000, itself at 2000:0000 and uses what comes after 5000:0000 for the memory allocator. This means RPM must fit into 64KB.

The latest RPM commit produces an image which is larger than that and, due to the loading mechanism that load files in 32KB chunks, it must be rounded up to 96KB. The last chunk overlaps with XOSL itself and trashes its memory as soon as it is loaded, so the final call to the program (the assembly snippet) is not done because it is no longer there.

I moved XOSL 64KB up in the address space, as well as the start of the memory pool.

@h0ly0ne Can you test the code at https://github.com/binary-manu/xosl/tree/rpm-integration and report? It should work now.

P.S.: I also updated the Dockerfile because the image the container is based on was renamed.

**Comment by h0ly0ne** [comment]
Wow - flawless victory - I was currently taking a deep dive into getting XOSL + RPM to compile within an unemulated WIN95 image with the original tools and was not aware of your progress. Long story short my patch was more a less just increasing the memory locations for the pointers in memory:

```
	void *Ptr1 = (void *)0x10000000;
	void *Ptr2 = (void *)0x18000000;
	void *Ptr3 = (void *)0x20000000;
```

 - and as you already stated, crashed XOSL. This happens when you have no knowledge about Assembly and Memory Mapping at all - I was just suspecting that the ASM fragment above is just executing what has been dumped to the memory adress starting at 0x10000000.

I'll try your changes ASAP - I am just hoping that my modifications to the source (MAKEFILEs + Adaptions to C++ Memory Models) make the compilation more solid within the docker environment. Additionally I am trying to replicate the exact BuildTools being original used by the XOSL/RPM Authors.

**Comment by binary-manu** [comment]
The fix has been merged into the XOSL master branch. There is also a new 1.1.7 tag for this version. It comes with my own RPM 2.46 and allows for RPM to grow up to 128kB. In exchange, the space for XOSL itself has been reduced by 64kB.

If embedding a smaller version of RPM, remember that it must now consist of 3 segments, so you must include an extra image file full of junk to make XOSL happy.
